# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import users_db_accessor_pb2 as protos_dot_users__db__accessor__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/users_db_accessor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsersDbAccessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserPreferences = channel.unary_unary(
                '/usersdb.UsersDbAccessor/GetUserPreferences',
                request_serializer=protos_dot_users__db__accessor__pb2.ByEmailRequest.SerializeToString,
                response_deserializer=protos_dot_users__db__accessor__pb2.GetUserPreferencesResponse.FromString,
                _registered_method=True)
        self.UpdateUserByEmail = channel.unary_unary(
                '/usersdb.UsersDbAccessor/UpdateUserByEmail',
                request_serializer=protos_dot_users__db__accessor__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=protos_dot_users__db__accessor__pb2.UpdateUserResponse.FromString,
                _registered_method=True)
        self.DeleteUserByEmail = channel.unary_unary(
                '/usersdb.UsersDbAccessor/DeleteUserByEmail',
                request_serializer=protos_dot_users__db__accessor__pb2.ByEmailRequest.SerializeToString,
                response_deserializer=protos_dot_users__db__accessor__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/usersdb.UsersDbAccessor/CreateUser',
                request_serializer=protos_dot_users__db__accessor__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=protos_dot_users__db__accessor__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/usersdb.UsersDbAccessor/GetUser',
                request_serializer=protos_dot_users__db__accessor__pb2.ByIdRequest.SerializeToString,
                response_deserializer=protos_dot_users__db__accessor__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/usersdb.UsersDbAccessor/UpdateUser',
                request_serializer=protos_dot_users__db__accessor__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=protos_dot_users__db__accessor__pb2.UpdateUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/usersdb.UsersDbAccessor/DeleteUser',
                request_serializer=protos_dot_users__db__accessor__pb2.ByIdRequest.SerializeToString,
                response_deserializer=protos_dot_users__db__accessor__pb2.DeleteUserResponse.FromString,
                _registered_method=True)


class UsersDbAccessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserPreferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersDbAccessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPreferences,
                    request_deserializer=protos_dot_users__db__accessor__pb2.ByEmailRequest.FromString,
                    response_serializer=protos_dot_users__db__accessor__pb2.GetUserPreferencesResponse.SerializeToString,
            ),
            'UpdateUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserByEmail,
                    request_deserializer=protos_dot_users__db__accessor__pb2.UpdateUserRequest.FromString,
                    response_serializer=protos_dot_users__db__accessor__pb2.UpdateUserResponse.SerializeToString,
            ),
            'DeleteUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserByEmail,
                    request_deserializer=protos_dot_users__db__accessor__pb2.ByEmailRequest.FromString,
                    response_serializer=protos_dot_users__db__accessor__pb2.DeleteUserResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=protos_dot_users__db__accessor__pb2.CreateUserRequest.FromString,
                    response_serializer=protos_dot_users__db__accessor__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=protos_dot_users__db__accessor__pb2.ByIdRequest.FromString,
                    response_serializer=protos_dot_users__db__accessor__pb2.GetUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=protos_dot_users__db__accessor__pb2.UpdateUserRequest.FromString,
                    response_serializer=protos_dot_users__db__accessor__pb2.UpdateUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=protos_dot_users__db__accessor__pb2.ByIdRequest.FromString,
                    response_serializer=protos_dot_users__db__accessor__pb2.DeleteUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usersdb.UsersDbAccessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usersdb.UsersDbAccessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsersDbAccessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersdb.UsersDbAccessor/GetUserPreferences',
            protos_dot_users__db__accessor__pb2.ByEmailRequest.SerializeToString,
            protos_dot_users__db__accessor__pb2.GetUserPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersdb.UsersDbAccessor/UpdateUserByEmail',
            protos_dot_users__db__accessor__pb2.UpdateUserRequest.SerializeToString,
            protos_dot_users__db__accessor__pb2.UpdateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersdb.UsersDbAccessor/DeleteUserByEmail',
            protos_dot_users__db__accessor__pb2.ByEmailRequest.SerializeToString,
            protos_dot_users__db__accessor__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersdb.UsersDbAccessor/CreateUser',
            protos_dot_users__db__accessor__pb2.CreateUserRequest.SerializeToString,
            protos_dot_users__db__accessor__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersdb.UsersDbAccessor/GetUser',
            protos_dot_users__db__accessor__pb2.ByIdRequest.SerializeToString,
            protos_dot_users__db__accessor__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersdb.UsersDbAccessor/UpdateUser',
            protos_dot_users__db__accessor__pb2.UpdateUserRequest.SerializeToString,
            protos_dot_users__db__accessor__pb2.UpdateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usersdb.UsersDbAccessor/DeleteUser',
            protos_dot_users__db__accessor__pb2.ByIdRequest.SerializeToString,
            protos_dot_users__db__accessor__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
