
services:
  newsapi_accessor:
    build:
      context: .
      dockerfile: NewsAPIAccessor/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - redis
      - placement

    networks:
        - dapr-news-aggregator-network
    environment:
        - DAPR_HTTP_PORT=3500
        - DAPR_GRPC_PORT=50001

  dapr_sidecar_newsapi_accessor:
    image: daprio/daprd:edge
    command: [ "./daprd",
               "--app-id", "newsapi_accessor",
               "--app-port", "50051",
               "--app-protocol", "grpc",
               "--dapr-http-port", "3500",
               "--dapr-grpc-port", "50001"]

    depends_on:
      - newsapi_accessor
    network_mode: "service:newsapi_accessor"



  placement:
    image: "daprio/dapr"
    command: [ "./placement", "--port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-news-aggregator-network

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
        - dapr-news-aggregator-network
networks:
    dapr-news-aggregator-network:
        driver: bridge
volumes:
  postgres-data:
    driver: local

