
services:
  newsapi_accessor:
    build:
      context: .
      dockerfile: NewsAPIAccessor/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - redis
      - placement

    networks:
        - dapr-news-aggregator-network
    environment:
        - DAPR_HTTP_PORT=3500
        - DAPR_GRPC_PORT=50001

  dapr_sidecar_newsapi_accessor:
    image: daprio/daprd:edge
    command: [ "./daprd",
               "--app-id", "newsapi_accessor",
               "--app-port", "50051",
               "--app-protocol", "grpc",
               "--dapr-http-port", "3500",
               "--dapr-grpc-port", "50001"]

    depends_on:
      - newsapi_accessor
    network_mode: "service:newsapi_accessor"


  users_db_accessor:
    build:
      context: .
      dockerfile: UsersDBAccessor/Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - redis
      - placement
      - postgres_users_db
    networks:
        - dapr-news-aggregator-network
    environment:
        - DAPR_HTTP_PORT=3501
        - DAPR_GRPC_PORT=50002

  dapr_sidecar_users_db_accessor:
    image: daprio/daprd:edge
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: [ "./daprd",
               "--app-id", "users_db_accessor",
               "--app-port", "50052",
               "--app-protocol", "grpc",
               "--dapr-http-port", "3501",
               "--dapr-grpc-port", "50002"]
    depends_on:
      - users_db_accessor
    network_mode: "service:users_db_accessor"

  postgres_users_db:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_users_db
      - POSTGRES_DB_NAME=postgres_users_db
    ports:
      - "5432:5432"
    networks:
        - dapr-news-aggregator-network
    volumes:
        - postgres-data:/var/lib/postgresql/data



  placement:
    image: "daprio/dapr"
    command: [ "./placement", "--port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-news-aggregator-network

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
        - dapr-news-aggregator-network
networks:
    dapr-news-aggregator-network:
        driver: bridge
volumes:
  postgres-data:
    driver: local

